### ISSUE TITLE
import via .ckan file is not working

### ISSUE THREAD

**Issue by enkido** [NathanKell/RP1Hardmode#1]
followed the rp1 install guide, compatible versions 1.8, 1.9, adding mechjeb dev repository

Install from .ckan file

![image](https://user-images.githubusercontent.com/6398971/128708846-3865b402-1a2f-45f4-9ad0-53a4c44ba5ed.png)

choosing 
![image](https://user-images.githubusercontent.com/6398971/128709105-0ff53578-bf10-4365-b585-f6cee47fb9e3.png)

results in 
![image](https://user-images.githubusercontent.com/6398971/128709171-49e948a0-d0ec-4803-89fd-358dfffab890.png)

every other option leads to
![image](https://user-images.githubusercontent.com/6398971/128709349-ef3c354f-e2a8-4481-83f2-a9d028ffa7e5.png)
or
![image](https://user-images.githubusercontent.com/6398971/128709297-a1860ad4-b678-47ff-a71b-0c5f417c0fb4.png)

**Comment by NathanKell** [comment]
Yup, sorry, I need to update the .ckan here. I'm in the process of massively simplifying RP-1 install which is why I haven't touched this recently.
